project:
  type: website

website:
  title: "Stefan Hansen"
  navbar:
    left:
      - href: about.qmd
        text: Om
      - href: shinyapps.qmd
        text: Shiny apps
      - href: consultancy.qmd
        text: Rådgivning
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    email-obfuscation: javascript
    #link-external-newwindow: true




